android.useAndroidX=true
android.enableJetifier=false
org.gradle.java.home=C:/Program Files/Java/jdk-21

# --- Optimasi Performa Gradle ---
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8